/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JPanel;
import modelo.Reloj;
import modelo.Slide;

/**
 *
 * @author beatl
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    private Color VerdePrincipal = new Color(0,179,61);
    private Color VerdeOn = new Color(0,212,72);
    private RegistroAnimales ra;
    
    private Slide sl;
    public menu() {
        initComponents();
        setLocationRelativeTo(null);
        pnlBarraSuperior.setBackground(VerdePrincipal);
        sl = new Slide();
        ra = new RegistroAnimales();
        //Reloj r = new Reloj(lblClock);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBarraSuperior = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        pnlMenuLateral = new javax.swing.JPanel();
        btnRegistroVeterinario = new javax.swing.JButton();
        btnRegistroAnimales = new javax.swing.JButton();
        btnRegistroCuidador = new javax.swing.JButton();
        btnRegistroActividades = new javax.swing.JButton();
        btnReporteHabitat = new javax.swing.JButton();
        btnReporteVisitaMedica = new javax.swing.JButton();
        btnHistorialVisitas = new javax.swing.JButton();
        btnHistorialActividades = new javax.swing.JButton();
        btnHistorialHabitats = new javax.swing.JButton();
        btnPersonalAnimales = new javax.swing.JButton();
        btnPersonalVeterinarios = new javax.swing.JButton();
        btnPersonalCuidadores = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlMainMenu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(212, 255, 204));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1700, 1000));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBarraSuperior.setBackground(new java.awt.Color(0, 179, 61));
        pnlBarraSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setDefaultCapable(false);
        btnClose.setFocusPainted(false);
        btnClose.setFocusable(false);
        btnClose.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/closeClicked.png"))); // NOI18N
        btnClose.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/closeOn.png"))); // NOI18N
        btnClose.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/closeClicked.png"))); // NOI18N
        btnClose.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/closeClicked.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        pnlBarraSuperior.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, -1, 50));

        btnMinimize.setBackground(new java.awt.Color(255, 255, 255));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizar.png"))); // NOI18N
        btnMinimize.setBorder(null);
        btnMinimize.setBorderPainted(false);
        btnMinimize.setContentAreaFilled(false);
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimize.setFocusable(false);
        btnMinimize.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizarClicked.png"))); // NOI18N
        btnMinimize.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizarOn.png"))); // NOI18N
        btnMinimize.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizarClicked.png"))); // NOI18N
        btnMinimize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimizarClicked.png"))); // NOI18N
        pnlBarraSuperior.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, -1, 50));

        jLabel6.setBackground(new java.awt.Color(0, 115, 0));
        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 21)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 82, 0));
        jLabel6.setText("Integrated Zoo System");
        pnlBarraSuperior.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 240, 50));

        lblBuscar.setBackground(new java.awt.Color(78, 206, 68));
        lblBuscar.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscar.setText("Buscar ");
        lblBuscar.setBorder(null);
        lblBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblBuscarActionPerformed(evt);
            }
        });
        pnlBarraSuperior.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 180, 30));

        btnBuscar.setBackground(new java.awt.Color(78, 206, 68));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setDefaultCapable(false);
        btnBuscar.setFocusPainted(false);
        btnBuscar.setOpaque(true);
        pnlBarraSuperior.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, 30));

        btnHome.setBackground(new java.awt.Color(0, 179, 61));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        btnHome.setBorder(null);
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setFocusPainted(false);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setOpaque(true);
        btnHome.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/homeOn.png"))); // NOI18N
        pnlBarraSuperior.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 50, 50));

        getContentPane().add(pnlBarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 50));

        pnlMenuLateral.setBackground(new java.awt.Color(0, 179, 61));
        pnlMenuLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistroVeterinario.setBackground(new java.awt.Color(0, 179, 61));
        btnRegistroVeterinario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegistroVeterinario.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistroVeterinario.setText("Veterinario");
        btnRegistroVeterinario.setBorder(null);
        btnRegistroVeterinario.setBorderPainted(false);
        btnRegistroVeterinario.setContentAreaFilled(false);
        btnRegistroVeterinario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistroVeterinario.setDefaultCapable(false);
        btnRegistroVeterinario.setFocusPainted(false);
        btnRegistroVeterinario.setFocusable(false);
        btnRegistroVeterinario.setOpaque(true);
        btnRegistroVeterinario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistroVeterinarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistroVeterinarioMouseExited(evt);
            }
        });
        pnlMenuLateral.add(btnRegistroVeterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, 40));

        btnRegistroAnimales.setBackground(new java.awt.Color(0, 179, 61));
        btnRegistroAnimales.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegistroAnimales.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistroAnimales.setText("Animales");
        btnRegistroAnimales.setBorder(null);
        btnRegistroAnimales.setBorderPainted(false);
        btnRegistroAnimales.setContentAreaFilled(false);
        btnRegistroAnimales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistroAnimales.setDefaultCapable(false);
        btnRegistroAnimales.setFocusPainted(false);
        btnRegistroAnimales.setFocusable(false);
        btnRegistroAnimales.setOpaque(true);
        btnRegistroAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistroAnimalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistroAnimalesMouseExited(evt);
            }
        });
        btnRegistroAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroAnimalesActionPerformed(evt);
            }
        });
        pnlMenuLateral.add(btnRegistroAnimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 40));

        btnRegistroCuidador.setBackground(new java.awt.Color(0, 179, 61));
        btnRegistroCuidador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegistroCuidador.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistroCuidador.setText("Cuidador");
        btnRegistroCuidador.setBorder(null);
        btnRegistroCuidador.setBorderPainted(false);
        btnRegistroCuidador.setContentAreaFilled(false);
        btnRegistroCuidador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistroCuidador.setDefaultCapable(false);
        btnRegistroCuidador.setFocusPainted(false);
        btnRegistroCuidador.setFocusable(false);
        btnRegistroCuidador.setOpaque(true);
        btnRegistroCuidador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistroCuidadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistroCuidadorMouseExited(evt);
            }
        });
        pnlMenuLateral.add(btnRegistroCuidador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 40));

        btnRegistroActividades.setBackground(new java.awt.Color(0, 179, 61));
        btnRegistroActividades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegistroActividades.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistroActividades.setText("Actividades");
        btnRegistroActividades.setBorder(null);
        btnRegistroActividades.setBorderPainted(false);
        btnRegistroActividades.setContentAreaFilled(false);
        btnRegistroActividades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistroActividades.setDefaultCapable(false);
        btnRegistroActividades.setFocusPainted(false);
        btnRegistroActividades.setFocusable(false);
        btnRegistroActividades.setOpaque(true);
        btnRegistroActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistroActividadesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistroActividadesMouseExited(evt);
            }
        });
        pnlMenuLateral.add(btnRegistroActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 250, 40));

        btnReporteHabitat.setBackground(new java.awt.Color(0, 179, 61));
        btnReporteHabitat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReporteHabitat.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteHabitat.setText("Habitats");
        btnReporteHabitat.setBorder(null);
        btnReporteHabitat.setBorderPainted(false);
        btnReporteHabitat.setContentAreaFilled(false);
        btnReporteHabitat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporteHabitat.setDefaultCapable(false);
        btnReporteHabitat.setFocusPainted(false);
        btnReporteHabitat.setFocusable(false);
        btnReporteHabitat.setOpaque(true);
        btnReporteHabitat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReporteHabitatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReporteHabitatMouseExited(evt);
            }
        });
        pnlMenuLateral.add(btnReporteHabitat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 250, 40));

        btnReporteVisitaMedica.setBackground(new java.awt.Color(0, 179, 61));
        btnReporteVisitaMedica.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReporteVisitaMedica.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteVisitaMedica.setText("Visita Medica");
        btnReporteVisitaMedica.setBorder(null);
        btnReporteVisitaMedica.setBorderPainted(false);
        btnReporteVisitaMedica.setContentAreaFilled(false);
        btnReporteVisitaMedica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporteVisitaMedica.setDefaultCapable(false);
        btnReporteVisitaMedica.setFocusPainted(false);
        btnReporteVisitaMedica.setFocusable(false);
        btnReporteVisitaMedica.setOpaque(true);
        btnReporteVisitaMedica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReporteVisitaMedicaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReporteVisitaMedicaMouseExited(evt);
            }
        });
        btnReporteVisitaMedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteVisitaMedicaActionPerformed(evt);
            }
        });
        pnlMenuLateral.add(btnReporteVisitaMedica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 250, 40));

        btnHistorialVisitas.setBackground(new java.awt.Color(0, 179, 61));
        btnHistorialVisitas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnHistorialVisitas.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorialVisitas.setText("Visitas");
        btnHistorialVisitas.setBorder(null);
        btnHistorialVisitas.setBorderPainted(false);
        btnHistorialVisitas.setContentAreaFilled(false);
        btnHistorialVisitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorialVisitas.setDefaultCapable(false);
        btnHistorialVisitas.setFocusPainted(false);
        btnHistorialVisitas.setFocusable(false);
        btnHistorialVisitas.setOpaque(true);
        btnHistorialVisitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHistorialVisitasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHistorialVisitasMouseExited(evt);
            }
        });
        pnlMenuLateral.add(btnHistorialVisitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 250, 40));

        btnHistorialActividades.setBackground(new java.awt.Color(0, 179, 61));
        btnHistorialActividades.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnHistorialActividades.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorialActividades.setText("Actividades");
        btnHistorialActividades.setBorder(null);
        btnHistorialActividades.setBorderPainted(false);
        btnHistorialActividades.setContentAreaFilled(false);
        btnHistorialActividades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorialActividades.setDefaultCapable(false);
        btnHistorialActividades.setFocusPainted(false);
        btnHistorialActividades.setFocusable(false);
        btnHistorialActividades.setOpaque(true);
        btnHistorialActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHistorialActividadesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHistorialActividadesMouseExited(evt);
            }
        });
        pnlMenuLateral.add(btnHistorialActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 250, 40));

        btnHistorialHabitats.setBackground(new java.awt.Color(0, 179, 61));
        btnHistorialHabitats.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnHistorialHabitats.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorialHabitats.setText("Habitats");
        btnHistorialHabitats.setBorder(null);
        btnHistorialHabitats.setBorderPainted(false);
        btnHistorialHabitats.setContentAreaFilled(false);
        btnHistorialHabitats.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorialHabitats.setDefaultCapable(false);
        btnHistorialHabitats.setFocusPainted(false);
        btnHistorialHabitats.setFocusable(false);
        btnHistorialHabitats.setOpaque(true);
        btnHistorialHabitats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHistorialHabitatsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHistorialHabitatsMouseExited(evt);
            }
        });
        pnlMenuLateral.add(btnHistorialHabitats, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 250, 40));

        btnPersonalAnimales.setBackground(new java.awt.Color(0, 179, 61));
        btnPersonalAnimales.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPersonalAnimales.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonalAnimales.setText("Animales");
        btnPersonalAnimales.setBorder(null);
        btnPersonalAnimales.setBorderPainted(false);
        btnPersonalAnimales.setContentAreaFilled(false);
        btnPersonalAnimales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPersonalAnimales.setDefaultCapable(false);
        btnPersonalAnimales.setFocusPainted(false);
        btnPersonalAnimales.setFocusable(false);
        btnPersonalAnimales.setOpaque(true);
        btnPersonalAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPersonalAnimalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPersonalAnimalesMouseExited(evt);
            }
        });
        pnlMenuLateral.add(btnPersonalAnimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 250, 40));

        btnPersonalVeterinarios.setBackground(new java.awt.Color(0, 179, 61));
        btnPersonalVeterinarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPersonalVeterinarios.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonalVeterinarios.setText("Veterinarios");
        btnPersonalVeterinarios.setBorder(null);
        btnPersonalVeterinarios.setBorderPainted(false);
        btnPersonalVeterinarios.setContentAreaFilled(false);
        btnPersonalVeterinarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPersonalVeterinarios.setDefaultCapable(false);
        btnPersonalVeterinarios.setFocusPainted(false);
        btnPersonalVeterinarios.setFocusable(false);
        btnPersonalVeterinarios.setOpaque(true);
        btnPersonalVeterinarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPersonalVeterinariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPersonalVeterinariosMouseExited(evt);
            }
        });
        pnlMenuLateral.add(btnPersonalVeterinarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 250, 40));

        btnPersonalCuidadores.setBackground(new java.awt.Color(0, 179, 61));
        btnPersonalCuidadores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPersonalCuidadores.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonalCuidadores.setText("Cuidadores");
        btnPersonalCuidadores.setBorder(null);
        btnPersonalCuidadores.setBorderPainted(false);
        btnPersonalCuidadores.setContentAreaFilled(false);
        btnPersonalCuidadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPersonalCuidadores.setDefaultCapable(false);
        btnPersonalCuidadores.setFocusPainted(false);
        btnPersonalCuidadores.setFocusable(false);
        btnPersonalCuidadores.setOpaque(true);
        btnPersonalCuidadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPersonalCuidadoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPersonalCuidadoresMouseExited(evt);
            }
        });
        pnlMenuLateral.add(btnPersonalCuidadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 250, 40));

        jLabel1.setBackground(new java.awt.Color(0, 179, 61));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/personal.png"))); // NOI18N
        jLabel1.setText("Personal");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIconTextGap(10);
        jLabel1.setOpaque(true);
        jLabel1.setVerifyInputWhenFocusTarget(false);
        pnlMenuLateral.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 200, 40));

        jLabel3.setBackground(new java.awt.Color(0, 179, 61));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Registro.png"))); // NOI18N
        jLabel3.setText("Registros");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIconTextGap(10);
        jLabel3.setOpaque(true);
        jLabel3.setVerifyInputWhenFocusTarget(false);
        pnlMenuLateral.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 200, 40));

        jLabel4.setBackground(new java.awt.Color(0, 179, 61));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte.png"))); // NOI18N
        jLabel4.setText("Reportes");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel4.setIconTextGap(10);
        jLabel4.setOpaque(true);
        jLabel4.setVerifyInputWhenFocusTarget(false);
        pnlMenuLateral.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 200, 40));

        jLabel5.setBackground(new java.awt.Color(0, 179, 61));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial.png"))); // NOI18N
        jLabel5.setText("Historiales");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel5.setIconTextGap(10);
        jLabel5.setOpaque(true);
        jLabel5.setVerifyInputWhenFocusTarget(false);
        pnlMenuLateral.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 200, 40));

        getContentPane().add(pnlMenuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 250, 640));

        pnlMainMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlMainMenu.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlMainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 850, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnReporteVisitaMedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteVisitaMedicaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnReporteVisitaMedicaActionPerformed

    private void btnRegistroVeterinarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroVeterinarioMouseEntered
        // TODO add your handling code here:
        btnRegistroVeterinario.setBackground(VerdeOn);
    }//GEN-LAST:event_btnRegistroVeterinarioMouseEntered

    private void btnRegistroVeterinarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroVeterinarioMouseExited
        // TODO add your handling code here:
        btnRegistroVeterinario.setBackground(VerdePrincipal);
    }//GEN-LAST:event_btnRegistroVeterinarioMouseExited

    private void btnRegistroCuidadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroCuidadorMouseEntered
        // TODO add your handling code here:
        btnRegistroCuidador.setBackground(VerdeOn);
    }//GEN-LAST:event_btnRegistroCuidadorMouseEntered

    private void btnRegistroCuidadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroCuidadorMouseExited
        // TODO add your handling code here:
        btnRegistroCuidador.setBackground(VerdePrincipal);
    }//GEN-LAST:event_btnRegistroCuidadorMouseExited

    private void btnRegistroAnimalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroAnimalesMouseEntered
        // TODO add your handling code here:
        btnRegistroAnimales.setBackground(VerdeOn);
    }//GEN-LAST:event_btnRegistroAnimalesMouseEntered

    private void btnRegistroActividadesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroActividadesMouseExited
        // TODO add your handling code here:
        btnRegistroActividades.setBackground(VerdePrincipal);
    }//GEN-LAST:event_btnRegistroActividadesMouseExited

    private void btnRegistroAnimalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroAnimalesMouseExited
        // TODO add your handling code here:
        btnRegistroAnimales.setBackground(VerdePrincipal);
    }//GEN-LAST:event_btnRegistroAnimalesMouseExited

    private void btnRegistroActividadesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroActividadesMouseEntered
        // TODO add your handling code here:
        btnRegistroActividades.setBackground(VerdeOn);
    }//GEN-LAST:event_btnRegistroActividadesMouseEntered

    private void btnReporteVisitaMedicaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteVisitaMedicaMouseEntered
        // TODO add your handling code here:
        btnReporteVisitaMedica.setBackground(VerdeOn);
    }//GEN-LAST:event_btnReporteVisitaMedicaMouseEntered

    private void btnReporteVisitaMedicaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteVisitaMedicaMouseExited
        btnReporteVisitaMedica.setBackground(VerdePrincipal);
    }//GEN-LAST:event_btnReporteVisitaMedicaMouseExited

    private void btnReporteHabitatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteHabitatMouseEntered
        btnReporteHabitat.setBackground(VerdeOn);
    }//GEN-LAST:event_btnReporteHabitatMouseEntered

    private void btnReporteHabitatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteHabitatMouseExited
        // TODO add your handling code here:
        btnReporteHabitat.setBackground(VerdePrincipal);
    }//GEN-LAST:event_btnReporteHabitatMouseExited

    private void btnHistorialVisitasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialVisitasMouseEntered
        // TODO add your handling code here:
        btnHistorialVisitas.setBackground(VerdeOn);
    }//GEN-LAST:event_btnHistorialVisitasMouseEntered

    private void btnHistorialVisitasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialVisitasMouseExited
        // TODO add your handling code here:
        btnHistorialVisitas.setBackground(VerdePrincipal);
    }//GEN-LAST:event_btnHistorialVisitasMouseExited

    private void btnHistorialHabitatsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialHabitatsMouseExited
        // TODO add your handling code here:
        btnHistorialHabitats.setBackground(VerdePrincipal);
    }//GEN-LAST:event_btnHistorialHabitatsMouseExited

    private void btnHistorialHabitatsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialHabitatsMouseEntered
        // TODO add your handling code here:
        btnHistorialHabitats.setBackground(VerdeOn);
    }//GEN-LAST:event_btnHistorialHabitatsMouseEntered

    private void btnHistorialActividadesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialActividadesMouseEntered
        // TODO add your handling code here:
        btnHistorialActividades.setBackground(VerdeOn);
    }//GEN-LAST:event_btnHistorialActividadesMouseEntered

    private void btnHistorialActividadesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialActividadesMouseExited
        // TODO add your handling code here:
        btnHistorialActividades.setBackground(VerdePrincipal);
    }//GEN-LAST:event_btnHistorialActividadesMouseExited

    private void btnPersonalAnimalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalAnimalesMouseExited
        // TODO add your handling code here:
        btnPersonalAnimales.setBackground(VerdePrincipal);
    }//GEN-LAST:event_btnPersonalAnimalesMouseExited

    private void btnPersonalAnimalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalAnimalesMouseEntered
        // TODO add your handling code here:
        btnPersonalAnimales.setBackground(VerdeOn);
    }//GEN-LAST:event_btnPersonalAnimalesMouseEntered

    private void btnPersonalVeterinariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalVeterinariosMouseEntered
        // TODO add your handling code here:
        btnPersonalVeterinarios.setBackground(VerdeOn);
    }//GEN-LAST:event_btnPersonalVeterinariosMouseEntered

    private void btnPersonalVeterinariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalVeterinariosMouseExited
        // TODO add your handling code here:
        btnPersonalVeterinarios.setBackground(VerdePrincipal);
    }//GEN-LAST:event_btnPersonalVeterinariosMouseExited

    private void btnPersonalCuidadoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalCuidadoresMouseEntered
        // TODO add your handling code here:
        btnPersonalCuidadores.setBackground(VerdeOn);
    }//GEN-LAST:event_btnPersonalCuidadoresMouseEntered

    private void btnPersonalCuidadoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalCuidadoresMouseExited
        // TODO add your handling code here:
        btnPersonalCuidadores.setBackground(VerdePrincipal);
    }//GEN-LAST:event_btnPersonalCuidadoresMouseExited

    private void lblBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBuscarActionPerformed

    private void btnRegistroAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroAnimalesActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnRegistroAnimalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnClose;
    public javax.swing.JButton btnHistorialActividades;
    public javax.swing.JButton btnHistorialHabitats;
    public javax.swing.JButton btnHistorialVisitas;
    public javax.swing.JButton btnHome;
    public javax.swing.JButton btnMinimize;
    public javax.swing.JButton btnPersonalAnimales;
    public javax.swing.JButton btnPersonalCuidadores;
    public javax.swing.JButton btnPersonalVeterinarios;
    public javax.swing.JButton btnRegistroActividades;
    public javax.swing.JButton btnRegistroAnimales;
    public javax.swing.JButton btnRegistroCuidador;
    public javax.swing.JButton btnRegistroVeterinario;
    public javax.swing.JButton btnReporteHabitat;
    public javax.swing.JButton btnReporteVisitaMedica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JTextField lblBuscar;
    public javax.swing.JPanel pnlBarraSuperior;
    public javax.swing.JPanel pnlMainMenu;
    public javax.swing.JPanel pnlMenuLateral;
    // End of variables declaration//GEN-END:variables
}
